apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: app-policy
  namespace: demo
spec:
  endpointSelector:
    matchLabels:
      app: web
  ingress:
    - fromEndpoints:
        - matchLabels:
            role: gateway
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: cluster-egress-policy
specs:
  - endpointSelector:
      matchLabels:
        role: worker
    egress:
      - toEntities:
          - kube-apiserver
  - endpointSelector:
      matchLabels:
        role: gateway
    ingress:
      - fromEntities:
          - world
