Transform: AWS::Serverless-2016-10-31
Resources:
  Workflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Done
        States:
          Done:
            Type: Succeed
