// Copyright 2026 The Planwright Authors
// SPDX-License-Identifier: Apache-2.0

package terraform

import (
	"fmt"
	"slices"
	"strings"

	"github.com/steadytao/planwright/internal/artifact"
	"github.com/steadytao/planwright/internal/graph"
	"github.com/steadytao/planwright/internal/limits"
)

func Render(g graph.Graph) ([]artifact.File, error) {
	webapp, err := inspectWebApp(g)
	if err != nil {
		return nil, err
	}

	files := []artifact.File{
		{Path: "README.md", Data: []byte(renderReadme(g))},
		{Path: "versions.tf", Data: []byte(renderVersions())},
		{Path: "providers.tf", Data: []byte(renderProviders(g))},
		{Path: "variables.tf", Data: []byte(renderVariables(effectiveProfile(g)))},
		{Path: "network.tf", Data: []byte(renderNetwork())},
		{Path: "security-groups.tf", Data: []byte(renderSecurityGroups(webapp))},
		{Path: "iam.tf", Data: []byte(renderIAM())},
		{Path: "observability.tf", Data: []byte(renderObservability())},
		{Path: "app.tf", Data: []byte(renderApp(webapp))},
		{Path: "database.tf", Data: []byte(renderDatabase(webapp))},
		{Path: "outputs.tf", Data: []byte(renderOutputs())},
	}
	artifact.Sort(files)
	return files, nil
}

type webAppGraph struct {
	ALB     graph.Node
	App     graph.Node
	DB      graph.Node
	Region  string
	AppPort int
	DBPort  int
}

func inspectWebApp(g graph.Graph) (webAppGraph, error) {
	if g.Provider != "aws" {
		return webAppGraph{}, fmt.Errorf("terraform generator supports aws graphs only")
	}
	if profile := strings.TrimSpace(g.Profile); profile != "" && profile != "lab" {
		return webAppGraph{}, fmt.Errorf("terraform generator currently supports lab profile graphs only")
	}

	var albs []graph.Node
	var apps []graph.Node
	var databases []graph.Node
	var unsupported []string
	for _, node := range g.Nodes {
		switch node.Kind {
		case "aws.alb":
			albs = append(albs, node)
		case "aws.ecs.service":
			apps = append(apps, node)
		case "aws.rds.postgres":
			databases = append(databases, node)
		case "external.internet":
			continue
		default:
			unsupported = append(unsupported, node.Kind)
		}
	}

	if len(albs) != 1 || len(apps) != 1 || len(databases) != 1 {
		return webAppGraph{}, fmt.Errorf("terraform generator requires aws.alb, aws.ecs.service and aws.rds.postgres nodes exactly once; got aws.alb=%d, aws.ecs.service=%d, aws.rds.postgres=%d", len(albs), len(apps), len(databases))
	}
	if len(unsupported) > 0 {
		return webAppGraph{}, fmt.Errorf("terraform generator supports the single AWS web application pattern only; unsupported node kinds: %s", strings.Join(sortedStrings(unsupported), ", "))
	}

	result := webAppGraph{
		ALB:     albs[0],
		App:     apps[0],
		DB:      databases[0],
		Region:  strings.TrimSpace(g.Region),
		AppPort: intProperty(apps[0].Properties, "port", 8080),
		DBPort:  intProperty(databases[0].Properties, "port", 5432),
	}
	if result.AppPort < limits.MinNetworkPort || result.AppPort > limits.MaxNetworkPort {
		return webAppGraph{}, fmt.Errorf("application port %d is outside %d..%d", result.AppPort, limits.MinNetworkPort, limits.MaxNetworkPort)
	}
	if result.DBPort < limits.MinNetworkPort || result.DBPort > limits.MaxNetworkPort {
		return webAppGraph{}, fmt.Errorf("database port %d is outside %d..%d", result.DBPort, limits.MinNetworkPort, limits.MaxNetworkPort)
	}
	if public, ok := graph.BoolProperty(result.DB.Properties, "publicly_accessible"); ok && public {
		return webAppGraph{}, fmt.Errorf("terraform generator does not support publicly accessible database nodes")
	}
	if !hasInternetALBEdge(g, result.ALB.ID) {
		return webAppGraph{}, fmt.Errorf("terraform generator requires an internet-facing network.allow edge to %s on tcp/443", result.ALB.ID)
	}
	if !hasNetworkAllowEdge(g, result.ALB.ID, result.App.ID, result.AppPort) {
		return webAppGraph{}, fmt.Errorf("terraform generator requires a network.allow edge from %s to %s on tcp/%d", result.ALB.ID, result.App.ID, result.AppPort)
	}
	if !hasNetworkAllowEdge(g, result.App.ID, result.DB.ID, result.DBPort) {
		return webAppGraph{}, fmt.Errorf("terraform generator requires a network.allow edge from %s to %s on tcp/%d", result.App.ID, result.DB.ID, result.DBPort)
	}
	return result, nil
}

func renderReadme(g graph.Graph) string {
	return fmt.Sprintf(
		"# Generated Terraform/OpenTofu Review Pack\n\n"+
			"This directory was generated by Planwright for review.\n\n"+
			"It is a starter output for the Planwright AWS web application pattern. Review the files before running Terraform or OpenTofu commands. Planwright does not run provider installation, validation, planning or apply steps. Review constraints:\n"+
			"- Provider: %s\n"+
			"- Region: %s\n"+
			"- Profile: %s\n"+
			"- Lab networking: ECS tasks are placed in generated public subnets with `assign_public_ip = true` so the starter pack avoids a NAT Gateway. Treat this as a review/lab trade-off; move tasks to private egress before production-like use.\n",
		markdownCode(g.Provider),
		markdownCode(g.Region),
		markdownCode(effectiveProfile(g)),
	)
}

func renderVersions() string {
	return `terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0, < 7.0"
    }
  }
}
`
}

func renderProviders(g graph.Graph) string {
	return fmt.Sprintf(`provider "aws" {
  region = %q
}
`, g.Region)
}

func renderVariables(profile string) string {
	return fmt.Sprintf(`variable "project_name" {
  type        = string
  description = "Name prefix for generated Planwright review resources."
  default     = "planwright-webapp"
}

variable "container_image" {
  type        = string
  description = "Container image for the application task."
  default     = "public.ecr.aws/docker/library/nginx:latest"
}

variable "db_username" {
  type        = string
  description = "Database master username."
  default     = "planwright"
}

variable "db_password" {
  type        = string
  description = "Database master password. Supply this outside the generated files."
  sensitive   = true
}

variable "acm_certificate_arn" {
  type        = string
  description = "ACM certificate ARN for the HTTPS listener."
}

variable "tags" {
  type        = map(string)
  description = "Tags applied to generated resources."
  default = {
    ManagedBy = "planwright"
    Profile   = %q
  }
}
`, profile)
}

func renderNetwork() string {
	return `data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags                 = merge(var.tags, { Name = "${var.project_name}-vpc" })
}

resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id
  tags   = merge(var.tags, { Name = "${var.project_name}-igw" })
}

resource "aws_subnet" "public_a" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true
  tags                    = merge(var.tags, { Name = "${var.project_name}-public-a" })
}

resource "aws_subnet" "public_b" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.2.0/24"
  availability_zone       = data.aws_availability_zones.available.names[1]
  map_public_ip_on_launch = true
  tags                    = merge(var.tags, { Name = "${var.project_name}-public-b" })
}

resource "aws_subnet" "private_a" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.101.0/24"
  availability_zone = data.aws_availability_zones.available.names[0]
  tags              = merge(var.tags, { Name = "${var.project_name}-private-a" })
}

resource "aws_subnet" "private_b" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.102.0/24"
  availability_zone = data.aws_availability_zones.available.names[1]
  tags              = merge(var.tags, { Name = "${var.project_name}-private-b" })
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id
  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }
  tags = merge(var.tags, { Name = "${var.project_name}-public-rt" })
}

resource "aws_route_table_association" "public_a" {
  subnet_id      = aws_subnet.public_a.id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table_association" "public_b" {
  subnet_id      = aws_subnet.public_b.id
  route_table_id = aws_route_table.public.id
}
`
}

func renderSecurityGroups(webapp webAppGraph) string {
	return fmt.Sprintf(`resource "aws_security_group" "alb" {
  name        = "${var.project_name}-alb"
  description = "Allow public HTTPS to the load balancer."
  vpc_id      = aws_vpc.main.id

  ingress {
    description = "Public HTTPS entrypoint."
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(var.tags, { Name = "${var.project_name}-alb-sg" })
}

resource "aws_security_group" "app" {
  name        = "${var.project_name}-app"
  description = "Allow ALB traffic to the application."
  vpc_id      = aws_vpc.main.id

  ingress {
    description     = "Load balancer to application."
    from_port       = %[1]d
    to_port         = %[1]d
    protocol        = "tcp"
    security_groups = [aws_security_group.alb.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(var.tags, { Name = "${var.project_name}-app-sg" })
}

resource "aws_security_group" "db" {
  name        = "${var.project_name}-db"
  description = "Allow application traffic to PostgreSQL only."
  vpc_id      = aws_vpc.main.id

  ingress {
    description     = "Application to PostgreSQL."
    from_port       = %[2]d
    to_port         = %[2]d
    protocol        = "tcp"
    security_groups = [aws_security_group.app.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(var.tags, { Name = "${var.project_name}-db-sg" })
}
`, webapp.AppPort, webapp.DBPort)
}

func renderApp(webapp webAppGraph) string {
	return fmt.Sprintf(`resource "aws_ecs_cluster" "app" {
  name = "${var.project_name}-cluster"
  tags = var.tags
}

resource "aws_lb" "app" {
  name               = "${var.project_name}-alb"
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = [aws_subnet.public_a.id, aws_subnet.public_b.id]
  tags               = var.tags
}

resource "aws_lb_target_group" "app" {
  name        = "${var.project_name}-tg"
  port        = %[1]d
  protocol    = "HTTP"
  target_type = "ip"
  vpc_id      = aws_vpc.main.id
  tags        = var.tags
}

resource "aws_lb_listener" "https" {
  load_balancer_arn = aws_lb.app.arn
  port              = 443
  protocol          = "HTTPS"
  certificate_arn   = var.acm_certificate_arn

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.app.arn
  }
}

resource "aws_ecs_task_definition" "app" {
  family                   = "${var.project_name}-task"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "256"
  memory                   = "512"
  execution_role_arn       = aws_iam_role.ecs_task_execution.arn

  container_definitions = jsonencode([
    {
      name      = "app"
      image     = var.container_image
      essential = true
      portMappings = [
        {
          containerPort = %[1]d
          protocol      = "tcp"
        }
      ]
      logConfiguration = {
        logDriver = "awslogs"
        options = {
          awslogs-group         = aws_cloudwatch_log_group.app.name
          awslogs-region        = %[2]q
          awslogs-stream-prefix = "app"
        }
      }
    }
  ])
}

resource "aws_ecs_service" "app" {
  name            = "${var.project_name}-service"
  cluster         = aws_ecs_cluster.app.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = [aws_subnet.public_a.id, aws_subnet.public_b.id]
    security_groups  = [aws_security_group.app.id]
    assign_public_ip = true
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.app.arn
    container_name   = "app"
    container_port   = %[1]d
  }
}
`, webapp.AppPort, webapp.Region)
}

func renderDatabase(webapp webAppGraph) string {
	return fmt.Sprintf(`resource "aws_db_subnet_group" "app" {
  name       = "${var.project_name}-db-subnets"
  subnet_ids = [aws_subnet.private_a.id, aws_subnet.private_b.id]
  tags       = var.tags
}

resource "aws_db_instance" "app" {
  identifier             = "${var.project_name}-db"
  engine                 = "postgres"
  instance_class         = "db.t4g.micro"
  allocated_storage      = 20
  db_subnet_group_name   = aws_db_subnet_group.app.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false
  port                   = %[1]d
  username               = var.db_username
  password               = var.db_password
  skip_final_snapshot    = true
  deletion_protection    = false
  tags                   = var.tags
}
`, webapp.DBPort)
}

func renderOutputs() string {
	return `output "load_balancer_dns_name" {
  value       = aws_lb.app.dns_name
  description = "DNS name of the generated application load balancer."
}

output "database_endpoint" {
  value       = aws_db_instance.app.endpoint
  description = "Database endpoint. Do not expose this publicly."
  sensitive   = true
}
`
}

func renderIAM() string {
	return `data "aws_iam_policy_document" "ecs_task_assume_role" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["ecs-tasks.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ecs_task_execution" {
  name               = "${var.project_name}-ecs-task-execution"
  assume_role_policy = data.aws_iam_policy_document.ecs_task_assume_role.json
  tags               = var.tags
}

resource "aws_iam_role_policy_attachment" "ecs_task_execution" {
  role       = aws_iam_role.ecs_task_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}
`
}

func renderObservability() string {
	return `resource "aws_cloudwatch_log_group" "app" {
  name              = "/aws/ecs/${var.project_name}"
  retention_in_days = 14
  tags              = var.tags
}
`
}

func intProperty(properties map[string]any, key string, fallback int) int {
	if properties == nil {
		return fallback
	}
	value, ok := properties[key]
	if !ok {
		return fallback
	}
	intValue, ok := value.(int)
	if !ok {
		return fallback
	}
	return intValue
}

func hasInternetALBEdge(g graph.Graph, albID string) bool {
	for _, edge := range g.Edges {
		if graph.IsInternetFacingNetworkAllow(g, edge) && edge.To == albID && edge.Protocol == "tcp" && edge.Port == 443 {
			return true
		}
	}
	return false
}

func hasNetworkAllowEdge(g graph.Graph, from string, to string, port int) bool {
	for _, edge := range g.Edges {
		if edge.From == from && edge.To == to && edge.Kind == "network.allow" && edge.Protocol == "tcp" && edge.Port == port {
			return true
		}
	}
	return false
}

func effectiveProfile(g graph.Graph) string {
	profile := strings.TrimSpace(g.Profile)
	if profile == "" {
		return "lab"
	}
	return profile
}

func sortedStrings(values []string) []string {
	out := append([]string(nil), values...)
	slices.Sort(out)
	return out
}

func markdownCode(value string) string {
	clean := markdownInline(value)
	backticks := longestBacktickRun(clean) + 1
	fence := strings.Repeat("`", backticks)
	if strings.Contains(clean, "`") {
		return fence + " " + clean + " " + fence
	}
	return fence + clean + fence
}

func markdownInline(value string) string {
	value = strings.ReplaceAll(value, "\r\n", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\t", " ")
	return strings.Join(strings.Fields(value), " ")
}

func longestBacktickRun(value string) int {
	longest := 0
	current := 0
	for _, char := range value {
		if char == '`' {
			current++
			if current > longest {
				longest = current
			}
			continue
		}
		current = 0
	}
	return longest
}
